# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "CodeCaf Blogs"

# A description of your site for social meta tag, search engines, and feed.xml
description: "CodeCaf Limited Blogs."

# Tagline near the site title
tagline: "Thoughts, stories and ideas."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://codecaf.nz"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guides
  url: /style-guide/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: blog-codecaf-nz

# Author information - author info at the bottom of the post
authors:
  ebby:
    name: Ebby Peter
    display_name: Ebby
    gravatar: e58b07f34f2171849b5cfedb351c37c8
    author_image: /images/ebby.png
    author_location: "Wellington, New Zealand"
    author_bio: "Ebby's Bio comes here..."
    email: ebby@codecaf.nz
    web: http://ebbypeter.com
    twitter: ebbypeter
    github: ebbpeter
  deepa:
    name: Deepika Jovy
    display_name: Deepa
    gravatar: 8c7e1f09300fb98dd983889ad904c3df
    author_image: /images/deepa.jpg
    author_location: "Wellington, New Zealand"
    author_bio: "Deepika's bio comes here..."
    email: deepika@codecaf.nz
    web: http://deepikajovy.github.io
    #twitter: company
    github: deepikajovy 
  sreejith:
    name: Sreejith Sukumaran
    display_name: Sreejth
    gravatar: 
    author_image: /images/no_profile_picture.jpg
    author_location: "Wellington, New Zealand"
    author_bio: "Sreejith's bio comes here..."
    email: sreejith@codecaf.nz
    web: 
    #twitter: company
    github:  
  anjali:
    name: Anjali Aravind
    display_name: Anjali
    gravatar: 
    author_image: /images/no_profile_picture.jpg
    author_location: "Wellington, New Zealand"
    author_bio: "Anjali's bio comes here..."
    email: anjali@codecaf.nz
    web: 
    #twitter: company
    github:  
  prasad:
    name: Prasad Madhavan
    display_name: Prasad
    gravatar: 
    author_image: /images/no_profile_picture.jpg
    author_location: "Wellington, New Zealand"
    author_bio: "Prasad's bio comes here..."
    email: prasad@codecaf.nz
    web: 
    #twitter: company
    github:  

# Sidebar Add banner
banner_url: "http://codecaf.nz"
banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
#twitter_username: 
#facebook_username: 
#googleplus_username: 
#codepen_username: 
#dribbble_uername: 
#medium_username: 
#instagram_username: 
#pinterest_username: 
github_username: "username"
linkedin_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
